version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres_bot
    restart: always
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: suscripciones
      TZ: UTC-3
      PGTZ: UTC-3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

